/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WWorkspaceSlugRouteImport } from './routes/w.$workspaceSlug'
import { Route as WWorkspaceSlugIndexRouteImport } from './routes/w.$workspaceSlug.index'
import { Route as WWorkspaceSlugConnectorsIndexRouteImport } from './routes/w.$workspaceSlug.connectors.index'
import { Route as WWorkspaceSlugConnectorsConnectorIdRouteImport } from './routes/w.$workspaceSlug.connectors.$connectorId'
import { Route as WWorkspaceSlugRoutinesIndexRouteImport } from './routes/w.$workspaceSlug.routines.index'
import { Route as WWorkspaceSlugRoutinesRoutineIdRouteImport } from './routes/w.$workspaceSlug.routines.$routineId'
import { Route as WWorkspaceSlugSettingsMembersRouteImport } from './routes/w.$workspaceSlug.settings.members'
import { Route as WWorkspaceSlugSkillsIndexRouteImport } from './routes/w.$workspaceSlug.skills.index'
import { Route as WWorkspaceSlugSkillsSlugRouteImport } from './routes/w.$workspaceSlug.skills.$slug'
import { Route as WWorkspaceSlugWikiIndexRouteImport } from './routes/w.$workspaceSlug.wiki.index'
import { Route as WWorkspaceSlugWikiSplatRouteImport } from './routes/w.$workspaceSlug.wiki.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceSlugRoute = WWorkspaceSlugRouteImport.update({
  id: '/w/$workspaceSlug',
  path: '/w/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceSlugIndexRoute = WWorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceSlugRoute,
} as any)
const WWorkspaceSlugConnectorsIndexRoute =
  WWorkspaceSlugConnectorsIndexRouteImport.update({
    id: '/connectors/',
    path: '/connectors/',
    getParentRoute: () => WWorkspaceSlugRoute,
  } as any)
const WWorkspaceSlugConnectorsConnectorIdRoute =
  WWorkspaceSlugConnectorsConnectorIdRouteImport.update({
    id: '/connectors/$connectorId',
    path: '/connectors/$connectorId',
    getParentRoute: () => WWorkspaceSlugRoute,
  } as any)
const WWorkspaceSlugRoutinesIndexRoute =
  WWorkspaceSlugRoutinesIndexRouteImport.update({
    id: '/routines/',
    path: '/routines/',
    getParentRoute: () => WWorkspaceSlugRoute,
  } as any)
const WWorkspaceSlugRoutinesRoutineIdRoute =
  WWorkspaceSlugRoutinesRoutineIdRouteImport.update({
    id: '/routines/$routineId',
    path: '/routines/$routineId',
    getParentRoute: () => WWorkspaceSlugRoute,
  } as any)
const WWorkspaceSlugSettingsMembersRoute =
  WWorkspaceSlugSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => WWorkspaceSlugRoute,
  } as any)
const WWorkspaceSlugSkillsIndexRoute =
  WWorkspaceSlugSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => WWorkspaceSlugRoute,
  } as any)
const WWorkspaceSlugSkillsSlugRoute =
  WWorkspaceSlugSkillsSlugRouteImport.update({
    id: '/skills/$slug',
    path: '/skills/$slug',
    getParentRoute: () => WWorkspaceSlugRoute,
  } as any)
const WWorkspaceSlugWikiIndexRoute = WWorkspaceSlugWikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => WWorkspaceSlugRoute,
} as any)
const WWorkspaceSlugWikiSplatRoute = WWorkspaceSlugWikiSplatRouteImport.update({
  id: '/wiki/$',
  path: '/wiki/$',
  getParentRoute: () => WWorkspaceSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/w/$workspaceSlug': typeof WWorkspaceSlugRouteWithChildren
  '/w/$workspaceSlug/': typeof WWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/connectors/$connectorId': typeof WWorkspaceSlugConnectorsConnectorIdRoute
  '/w/$workspaceSlug/routines/$routineId': typeof WWorkspaceSlugRoutinesRoutineIdRoute
  '/w/$workspaceSlug/settings/members': typeof WWorkspaceSlugSettingsMembersRoute
  '/w/$workspaceSlug/skills/$slug': typeof WWorkspaceSlugSkillsSlugRoute
  '/w/$workspaceSlug/wiki/$': typeof WWorkspaceSlugWikiSplatRoute
  '/w/$workspaceSlug/connectors/': typeof WWorkspaceSlugConnectorsIndexRoute
  '/w/$workspaceSlug/routines/': typeof WWorkspaceSlugRoutinesIndexRoute
  '/w/$workspaceSlug/skills/': typeof WWorkspaceSlugSkillsIndexRoute
  '/w/$workspaceSlug/wiki/': typeof WWorkspaceSlugWikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/w/$workspaceSlug': typeof WWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/connectors/$connectorId': typeof WWorkspaceSlugConnectorsConnectorIdRoute
  '/w/$workspaceSlug/routines/$routineId': typeof WWorkspaceSlugRoutinesRoutineIdRoute
  '/w/$workspaceSlug/settings/members': typeof WWorkspaceSlugSettingsMembersRoute
  '/w/$workspaceSlug/skills/$slug': typeof WWorkspaceSlugSkillsSlugRoute
  '/w/$workspaceSlug/wiki/$': typeof WWorkspaceSlugWikiSplatRoute
  '/w/$workspaceSlug/connectors': typeof WWorkspaceSlugConnectorsIndexRoute
  '/w/$workspaceSlug/routines': typeof WWorkspaceSlugRoutinesIndexRoute
  '/w/$workspaceSlug/skills': typeof WWorkspaceSlugSkillsIndexRoute
  '/w/$workspaceSlug/wiki': typeof WWorkspaceSlugWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/w/$workspaceSlug': typeof WWorkspaceSlugRouteWithChildren
  '/w/$workspaceSlug/': typeof WWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/connectors/$connectorId': typeof WWorkspaceSlugConnectorsConnectorIdRoute
  '/w/$workspaceSlug/routines/$routineId': typeof WWorkspaceSlugRoutinesRoutineIdRoute
  '/w/$workspaceSlug/settings/members': typeof WWorkspaceSlugSettingsMembersRoute
  '/w/$workspaceSlug/skills/$slug': typeof WWorkspaceSlugSkillsSlugRoute
  '/w/$workspaceSlug/wiki/$': typeof WWorkspaceSlugWikiSplatRoute
  '/w/$workspaceSlug/connectors/': typeof WWorkspaceSlugConnectorsIndexRoute
  '/w/$workspaceSlug/routines/': typeof WWorkspaceSlugRoutinesIndexRoute
  '/w/$workspaceSlug/skills/': typeof WWorkspaceSlugSkillsIndexRoute
  '/w/$workspaceSlug/wiki/': typeof WWorkspaceSlugWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dev-login'
    | '/login'
    | '/w/$workspaceSlug'
    | '/w/$workspaceSlug/'
    | '/w/$workspaceSlug/connectors/$connectorId'
    | '/w/$workspaceSlug/routines/$routineId'
    | '/w/$workspaceSlug/settings/members'
    | '/w/$workspaceSlug/skills/$slug'
    | '/w/$workspaceSlug/wiki/$'
    | '/w/$workspaceSlug/connectors/'
    | '/w/$workspaceSlug/routines/'
    | '/w/$workspaceSlug/skills/'
    | '/w/$workspaceSlug/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dev-login'
    | '/login'
    | '/w/$workspaceSlug'
    | '/w/$workspaceSlug/connectors/$connectorId'
    | '/w/$workspaceSlug/routines/$routineId'
    | '/w/$workspaceSlug/settings/members'
    | '/w/$workspaceSlug/skills/$slug'
    | '/w/$workspaceSlug/wiki/$'
    | '/w/$workspaceSlug/connectors'
    | '/w/$workspaceSlug/routines'
    | '/w/$workspaceSlug/skills'
    | '/w/$workspaceSlug/wiki'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dev-login'
    | '/login'
    | '/w/$workspaceSlug'
    | '/w/$workspaceSlug/'
    | '/w/$workspaceSlug/connectors/$connectorId'
    | '/w/$workspaceSlug/routines/$routineId'
    | '/w/$workspaceSlug/settings/members'
    | '/w/$workspaceSlug/skills/$slug'
    | '/w/$workspaceSlug/wiki/$'
    | '/w/$workspaceSlug/connectors/'
    | '/w/$workspaceSlug/routines/'
    | '/w/$workspaceSlug/skills/'
    | '/w/$workspaceSlug/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DevLoginRoute: typeof DevLoginRoute
  LoginRoute: typeof LoginRoute
  WWorkspaceSlugRoute: typeof WWorkspaceSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceSlug': {
      id: '/w/$workspaceSlug'
      path: '/w/$workspaceSlug'
      fullPath: '/w/$workspaceSlug'
      preLoaderRoute: typeof WWorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceSlug/': {
      id: '/w/$workspaceSlug/'
      path: '/'
      fullPath: '/w/$workspaceSlug/'
      preLoaderRoute: typeof WWorkspaceSlugIndexRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/connectors/': {
      id: '/w/$workspaceSlug/connectors/'
      path: '/connectors'
      fullPath: '/w/$workspaceSlug/connectors/'
      preLoaderRoute: typeof WWorkspaceSlugConnectorsIndexRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/connectors/$connectorId': {
      id: '/w/$workspaceSlug/connectors/$connectorId'
      path: '/connectors/$connectorId'
      fullPath: '/w/$workspaceSlug/connectors/$connectorId'
      preLoaderRoute: typeof WWorkspaceSlugConnectorsConnectorIdRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/routines/': {
      id: '/w/$workspaceSlug/routines/'
      path: '/routines'
      fullPath: '/w/$workspaceSlug/routines/'
      preLoaderRoute: typeof WWorkspaceSlugRoutinesIndexRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/routines/$routineId': {
      id: '/w/$workspaceSlug/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/w/$workspaceSlug/routines/$routineId'
      preLoaderRoute: typeof WWorkspaceSlugRoutinesRoutineIdRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/settings/members': {
      id: '/w/$workspaceSlug/settings/members'
      path: '/settings/members'
      fullPath: '/w/$workspaceSlug/settings/members'
      preLoaderRoute: typeof WWorkspaceSlugSettingsMembersRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/skills/': {
      id: '/w/$workspaceSlug/skills/'
      path: '/skills'
      fullPath: '/w/$workspaceSlug/skills/'
      preLoaderRoute: typeof WWorkspaceSlugSkillsIndexRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/skills/$slug': {
      id: '/w/$workspaceSlug/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/w/$workspaceSlug/skills/$slug'
      preLoaderRoute: typeof WWorkspaceSlugSkillsSlugRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/wiki/': {
      id: '/w/$workspaceSlug/wiki/'
      path: '/wiki'
      fullPath: '/w/$workspaceSlug/wiki/'
      preLoaderRoute: typeof WWorkspaceSlugWikiIndexRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/wiki/$': {
      id: '/w/$workspaceSlug/wiki/$'
      path: '/wiki/$'
      fullPath: '/w/$workspaceSlug/wiki/$'
      preLoaderRoute: typeof WWorkspaceSlugWikiSplatRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
  }
}

interface WWorkspaceSlugRouteChildren {
  WWorkspaceSlugIndexRoute: typeof WWorkspaceSlugIndexRoute
  WWorkspaceSlugConnectorsConnectorIdRoute: typeof WWorkspaceSlugConnectorsConnectorIdRoute
  WWorkspaceSlugRoutinesRoutineIdRoute: typeof WWorkspaceSlugRoutinesRoutineIdRoute
  WWorkspaceSlugSettingsMembersRoute: typeof WWorkspaceSlugSettingsMembersRoute
  WWorkspaceSlugSkillsSlugRoute: typeof WWorkspaceSlugSkillsSlugRoute
  WWorkspaceSlugWikiSplatRoute: typeof WWorkspaceSlugWikiSplatRoute
  WWorkspaceSlugConnectorsIndexRoute: typeof WWorkspaceSlugConnectorsIndexRoute
  WWorkspaceSlugRoutinesIndexRoute: typeof WWorkspaceSlugRoutinesIndexRoute
  WWorkspaceSlugSkillsIndexRoute: typeof WWorkspaceSlugSkillsIndexRoute
  WWorkspaceSlugWikiIndexRoute: typeof WWorkspaceSlugWikiIndexRoute
}

const WWorkspaceSlugRouteChildren: WWorkspaceSlugRouteChildren = {
  WWorkspaceSlugIndexRoute: WWorkspaceSlugIndexRoute,
  WWorkspaceSlugConnectorsConnectorIdRoute:
    WWorkspaceSlugConnectorsConnectorIdRoute,
  WWorkspaceSlugRoutinesRoutineIdRoute: WWorkspaceSlugRoutinesRoutineIdRoute,
  WWorkspaceSlugSettingsMembersRoute: WWorkspaceSlugSettingsMembersRoute,
  WWorkspaceSlugSkillsSlugRoute: WWorkspaceSlugSkillsSlugRoute,
  WWorkspaceSlugWikiSplatRoute: WWorkspaceSlugWikiSplatRoute,
  WWorkspaceSlugConnectorsIndexRoute: WWorkspaceSlugConnectorsIndexRoute,
  WWorkspaceSlugRoutinesIndexRoute: WWorkspaceSlugRoutinesIndexRoute,
  WWorkspaceSlugSkillsIndexRoute: WWorkspaceSlugSkillsIndexRoute,
  WWorkspaceSlugWikiIndexRoute: WWorkspaceSlugWikiIndexRoute,
}

const WWorkspaceSlugRouteWithChildren = WWorkspaceSlugRoute._addFileChildren(
  WWorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DevLoginRoute: DevLoginRoute,
  LoginRoute: LoginRoute,
  WWorkspaceSlugRoute: WWorkspaceSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
